### ISSUE TITLE
AADSTS500013 - Resourse identifier is not provided

### ISSUE THREAD

**Issue by NevillePerkins** [damienbod/dotnet-template-angular#9]
Thanks for this cool template and upgrading to the latest frameworks!

Can you kindly give any suggestions as what I might have missed as I'm getting above error after logging in with my Azure AD details.

![image](https://user-images.githubusercontent.com/8456416/68299719-eed82280-00a4-11ea-8900-8b5701b5e0d4.png)

**Comment by NevillePHolistics** [comment]
I don't remember how I fixed it but this is no longer an issue. You can close this.
